-- Demo theo giao diện hiện tại; mặc định là nháp. URL example.com là placeholder.
-- Ảnh assets/ là ảnh demo cục bộ; thay bằng URL Storage khi triển khai.
begin;
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('s1','Nhạc hội Awaken – Trường Đại học Thăng Long','2026-10-02',NULL,'18:00','21:00',ARRAY['Event']::text[],'Hà Nội',NULL,NULL,NULL,NULL,NULL,ARRAY[]::text[],NULL,NULL,1,false) on conflict(legacy_id) do nothing;
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('s2','The New Era Concert','2026-10-03',NULL,'19:00','22:00',ARRAY['Concert','Livestream']::text[],'Trung tâm Hội nghị Quốc gia, Hà Nội',NULL,'https://maps.google.com','https://example.com','Thông báo chính thức từ BTC',NULL,ARRAY['Hãy tuân thủ quy định của BTC.','Không quay chụp ở khu vực hạn chế.','Giữ trật tự, văn minh và an toàn.']::text[],'The New Era Concert – cùng Cường Bạch rực sáng!',NULL,2,false) on conflict(legacy_id) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#CuongBach',0 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#UPRIZE',1 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#UPRIZE_BEX',2 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#TheNewEra',3 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#FM127MHZ',4 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#CuongBach',0 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#UPRIZE',1 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#UPRIZE_BEX',2 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#TheNewEra',3 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#FM127MHZ',4 from public.events where legacy_id='s2' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_links(event_id,title,url,sort_order) select id,'Link livestream (YouTube)','https://youtube.com/@cuongbach',0 from public.events e where legacy_id='s2' and not exists(select 1 from public.event_links c where c.event_id=e.id and c.title='Link livestream (YouTube)');
insert into public.event_links(event_id,title,url,sort_order) select id,'Hướng dẫn tham gia','https://example.com/huong-dan',1 from public.events e where legacy_id='s2' and not exists(select 1 from public.event_links c where c.event_id=e.id and c.title='Hướng dẫn tham gia');
insert into public.event_images(event_id,image_url,caption,sort_order) select id,'assets/page-background.jpg','Ảnh demo 1 · Chân dung',0 from public.events e where legacy_id='s2' and not exists(select 1 from public.event_images c where c.event_id=e.id and c.image_url='assets/page-background.jpg');
insert into public.event_images(event_id,image_url,caption,sort_order) select id,'assets/schedule-desktop.jpg','Ảnh demo 2 · Poster lịch trình',1 from public.events e where legacy_id='s2' and not exists(select 1 from public.event_images c where c.event_id=e.id and c.image_url='assets/schedule-desktop.jpg');
insert into public.event_images(event_id,image_url,caption,sort_order) select id,'assets/schedule-reference.jpg','Ảnh demo 3 · Poster desktop và mobile',2 from public.events e where legacy_id='s2' and not exists(select 1 from public.event_images c where c.event_id=e.id and c.image_url='assets/schedule-reference.jpg');
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('s3','Shopee Sao Thi Sao 2 – Shooting','2026-10-10',NULL,'08:00','18:00',ARRAY['Brand']::text[],'Hồ Chí Minh',NULL,NULL,NULL,NULL,NULL,ARRAY[]::text[],NULL,NULL,3,false) on conflict(legacy_id) do nothing;
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('s4','Fan Meeting – Hà Nội','2026-10-15',NULL,'18:00','21:00',ARRAY['Event']::text[],'Hà Nội',NULL,NULL,NULL,NULL,NULL,ARRAY[]::text[],NULL,NULL,4,false) on conflict(legacy_id) do nothing;
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('s5','Show truyền hình XYZ','2026-10-20',NULL,'20:00','22:00',ARRAY['TV Show']::text[],'VTV3',NULL,NULL,NULL,NULL,NULL,ARRAY[]::text[],NULL,NULL,5,false) on conflict(legacy_id) do nothing;
insert into public.events(legacy_id,name,event_date,end_date,start_time,end_time,event_types,location,thumbnail_url,map_url,source_url,source_label,description,notes,threads_topic,keyword,sort_order,is_published) values('demo-today','Giao lưu cùng Cường Bạch – Demo hôm nay','2026-10-06',NULL,'19:00','21:00',ARRAY['Event','Livestream']::text[],'Hà Nội · Dữ liệu minh họa',NULL,NULL,NULL,NULL,NULL,ARRAY['Sự kiện demo để minh họa giao diện, không phải lịch trình thực tế.']::text[],'Cùng chờ buổi giao lưu tối nay với Cường Bạch! ✨','Cường Bạch giao lưu',0,false) on conflict(legacy_id) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'Facebook','#CuongBach',0 from public.events where legacy_id='demo-today' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_hashtags(event_id,platform,hashtag,sort_order) select id,'TikTok','#CuongBach',0 from public.events where legacy_id='demo-today' on conflict(event_id,platform,hashtag) do nothing;
insert into public.event_images(event_id,image_url,caption,sort_order) select id,'assets/page-background.jpg',NULL,0 from public.events e where legacy_id='demo-today' and not exists(select 1 from public.event_images c where c.event_id=e.id and c.image_url='assets/page-background.jpg');
commit;
